# Generated by Django 2.2.3 on 2019-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_date_time', models.DateTimeField(verbose_name='Recording Date-Time')),
                ('night_number', models.IntegerField(default=0, verbose_name='Night Number')),
                ('in_night_index', models.IntegerField(default=0, verbose_name='Index in Night')),
                ('alias', models.CharField(default='Landcode_LocAfk_ProjAfk_YR_Afk_NightNr_InNightIndex', max_length=200)),
                ('audio_file', models.FileField(max_length=512, upload_to='tmp')),
                ('original_filename', models.CharField(blank=True, max_length=100, null=True, verbose_name='Org. Filename')),
                ('sample_frequency', models.IntegerField(blank=True, null=True, verbose_name='Samplefrequency (Hz)')),
                ('sample_count', models.IntegerField(blank=True, null=True, verbose_name='# Samples')),
                ('sample_width', models.IntegerField(blank=True, null=True, verbose_name='Samplewidth (Bits)')),
                ('channel_count', models.IntegerField(blank=True, null=True, verbose_name='Number of Channels')),
            ],
            options={
                'verbose_name': 'Sound',
                'verbose_name_plural': 'Sounds',
            },
        ),
    ]
