# Generated by Django 2.2.3 on 2019-07-11 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0003_auto_20190710_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatMusicSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Session under Development'), ('PUBL', 'Session Published')], default='OPEN', max_length=5, verbose_name='Status')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('recorder_text', models.CharField(blank=True, max_length=100, null=True, verbose_name="Text alternative for 'Recorder'")),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('recordingtime_in_dst', models.BooleanField(default=False, verbose_name='Recordingperiod has DST')),
                ('daylight_saving_correction', models.BooleanField(default=False, verbose_name='DST Correction Applied (by user)')),
                ('last_upload_trigger_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Last time Files have been uploaded')),
                ('last_upload_mtime', models.IntegerField(default=0, verbose_name='Last max mtime Uploaded Item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BatMusic Session',
                'verbose_name_plural': 'BatMusic Sessions',
            },
        ),
    ]
