# Generated by Django 2.2.3 on 2019-07-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_sound_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='audio_file',
            new_name='file',
        ),
    ]
