# Generated by Django 2.2.3 on 2019-07-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_auto_20190716_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='recording_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recording Date-Time'),
        ),
    ]
