# Generated by Django 2.2.4 on 2019-08-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0007_auto_20190716_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, upload_to='tmp', verbose_name='Archive File')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.BatMusicSession')),
            ],
        ),
    ]
